server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://82.157.150.224:5432/ins_db?useSSL=false
    username: liyu
    password: "00000000"

mybatis:
    mapper-locations: classpath*:mapper/*.xml